version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: Dockerコンテナの起動
          command: docker-compose -f test.yml up -d
      - run:
          name: データベースのセットアップ
          command: docker-compose run app rails db:create RAILS_ENV=test --trace
      - run:
          name: RSpecテスト実行
          command: docker-compose run app bundle exec bin/rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down

# version: 2
# jobs:
#   build:
#     machine:
#       image: circleci/classic:edge
#     working_directory: ~/repo
#     steps:
#       - checkout
#       - run:
#           name: Install Docker Compose
#           command: |
#             curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
#             chmod +x ~/docker-compose
#             sudo mv ~/docker-compose /usr/local/bin/docker-compose
#       - run:
#           name: docker-compose -f test.yml up
#           command: |
#             set -x
#             docker-compose up --build -d
#       - run:
#           name: docker-compose stop
#           command: |
#             set -x
#             docker-compose stop
#       - run:
#           name: docker-compose -f test.yml up
#           command: |
#             set -x
#             docker-compose up -f test.yml -d
#       - run:
#           name: test
#           command: |
#             mkdir /tmp/test-results
#             TEST_FILES="$(circleci tests glob 'spec/**/*_spec.rb' | circleci tests split --split-by=timings)"
#             docker-compose exec rails_api bin/rspec --format progress \
#                                                                   --format RspecJunitFormatter \
#                                                                   --out /tmp/test-results/rspec.xml \
#                                                                   $TEST_FILES
#       - run:
#           name: docker-compose down
#           command: docker-compose down